package com.ptpmud.quanlynhatro.view;

import com.ptpmud.quanlynhatro.model.DichVu;
import com.ptpmud.quanlynhatro.service.DichVuService;
import com.ptpmud.quanlynhatro.utils.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class DichVuGD extends javax.swing.JPanel {
    
   private final DichVuService service = new DichVuService();
    private DefaultTableModel dvModel;
    private JTable dvTable;
    
    public DichVuGD() {
        initComponents();
        setupTable();
        setupActions();
        loadData();
    }
    private void setupTable(){
         String[] cols = {"ID","Tên dịch vụ","Đơn giá","Mô tả"};
          dvModel = new DefaultTableModel(cols, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Không cho sửa trực tiếp trên bảng
            }
        };
        table.setModel(dvModel); // Gán model thực sự vào table
        table.setRowHeight(28);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAdd.setText("Thêm");

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btnEdit.setText("Sửa");

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDel.setText("Xóa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDel)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables


private void setupActions(){
        btnAdd.addActionListener(e -> showAddDialog());
        btnEdit.addActionListener(e -> showEditDialog());
        btnDel.addActionListener(e -> deleteSelected());
}
private void loadData() {
        List<DichVu> list = service.getAll();
        dvModel.setRowCount(0);

        for (DichVu d : list) {
            dvModel.addRow(new Object[]{
                d.getIdDichVu(),
                d.getTenDichVu(),
                d.getDonGia(),
                d.getMoTa()
            });
        }
    }
 private void showAddDialog() {
        JPanel p = new JPanel(new GridLayout(0,1,6,6));
        JTextField tName = new JTextField();
        JTextField tPrice = new JTextField();
        JTextArea tMoTa = new JTextArea(4,20);

        p.add(new JLabel("Tên dịch vụ:")); p.add(tName);
        p.add(new JLabel("Đơn giá:")); p.add(tPrice);
        p.add(new JLabel("Mô tả:")); p.add(new JScrollPane(tMoTa));

        int r = JOptionPane.showConfirmDialog(
                this, p, "Thêm dịch vụ",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE
        );

        if (r != JOptionPane.OK_OPTION) return;

        try {
            String name = tName.getText().trim();
            double price = Double.parseDouble(tPrice.getText().trim());

            if (name.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tên dịch vụ trống.");
                return;
            }

            DichVu dv = new DichVu();
            dv.setTenDichVu(name);
            dv.setDonGia(price);
            dv.setMoTa(tMoTa.getText().trim());

            if (service.create(dv)) {
                JOptionPane.showMessageDialog(this, "Đã thêm.");
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không hợp lệ: " + ex.getMessage(),
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void showEditDialog() {
        int sel = table.getSelectedRow();
        if (sel < 0) {
            JOptionPane.showMessageDialog(this, "Chọn dịch vụ để sửa.");
            return;
        }

        int id = (int) dvModel.getValueAt(sel, 0);
        DichVu dv = service.getById(id);

        if (dv == null) {
            JOptionPane.showMessageDialog(this, "Dịch vụ không tồn tại.");
            loadData();
            return;
        }

        JPanel p = new JPanel(new GridLayout(0,1,6,6));

        JTextField tName = new JTextField(dv.getTenDichVu());
        JTextField tPrice = new JTextField(String.valueOf((long) dv.getDonGia()));
        JTextArea tMoTa = new JTextArea(dv.getMoTa(),4,20);

        p.add(new JLabel("Tên dịch vụ:")); p.add(tName);
        p.add(new JLabel("Đơn giá:")); p.add(tPrice);
        p.add(new JLabel("Mô tả:")); p.add(new JScrollPane(tMoTa));

        int r = JOptionPane.showConfirmDialog(
                this, p, "Sửa dịch vụ",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE
        );

        if (r != JOptionPane.OK_OPTION) return;

        try {
            dv.setTenDichVu(tName.getText().trim());
            dv.setDonGia(Double.parseDouble(tPrice.getText().trim()));
            dv.setMoTa(tMoTa.getText().trim());

            if (service.update(dv)) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công.");
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại.",
                        "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không hợp lệ: " + ex.getMessage(),
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void deleteSelected() {
        int sel = table.getSelectedRow();
        if (sel < 0) {
            JOptionPane.showMessageDialog(this, "Chọn dịch vụ để xóa.");
            return;
        }

        int id = (int) dvModel.getValueAt(sel, 0);

        if (JOptionPane.showConfirmDialog(
                this, "Xóa dịch vụ ID=" + id + "?",
                "Xác nhận", JOptionPane.YES_NO_OPTION
        ) != JOptionPane.YES_OPTION) return;

        if (service.delete(id)) {
            JOptionPane.showMessageDialog(this, "Đã xóa.");
            loadData();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại (kiểm tra ràng buộc).",
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
}
