package com.ptpmud.quanlynhatro.view;

import com.ptpmud.quanlynhatro.model.KhachHang;
import com.ptpmud.quanlynhatro.model.TaiKhoan;
import com.ptpmud.quanlynhatro.service.KhachHangService;
import com.ptpmud.quanlynhatro.service.TaiKhoanService;
import com.ptpmud.quanlynhatro.utils.*;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class TaiKhoanGD extends javax.swing.JPanel {

    private final TaiKhoanService service = new TaiKhoanService();
    private final KhachHangService khachHangService = new KhachHangService();
    private DefaultTableModel model;

    public TaiKhoanGD() {
        initComponents();
        setupTable();
        setupActions();
        loadData();
    }

    private void setupTable() {
        String[] cols = {"ID", "Tên đăng nhập", "Họ tên", "Vai trò", "Khách hàng liên kết"};

        model = new DefaultTableModel(cols, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableACC.setModel(model);
        tableACC.setRowHeight(28);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReload = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableACC = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAdd.setText("Thêm");

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDelete.setText("Xóa");

        btnReload.setText("⟳.");
        btnReload.addActionListener(this::btnReloadActionPerformed);

        btnChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key.png"))); // NOI18N
        btnChangePassword.setText("Đổi MK");
        btnChangePassword.addActionListener(this::btnChangePasswordActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChangePassword)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReload)
                    .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tableACC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableACC);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReloadActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
          changePasswordForSelectedAccount();
    }//GEN-LAST:event_btnChangePasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReload;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableACC;
    // End of variables declaration//GEN-END:variables

    private void setupActions() {
        btnAdd.addActionListener(e -> showCreateDialog());
        btnDelete.addActionListener(e -> deleteSelected());
        btnReload.addActionListener(e -> loadData());
    }

    private void loadData() {
        List<TaiKhoan> list = service.findAll();
        model.setRowCount(0);
        for (TaiKhoan tk : list) {
            String khachHangInfo = "";
            if (tk.getIdKhachHang() != null) {
                KhachHang kh = khachHangService.findById(tk.getIdKhachHang());
                if (kh != null) {
                    khachHangInfo = kh.getTenKhachHang() + " (ID:" + kh.getIdKhachHang() + ")";
                }
            }
            model.addRow(new Object[]{tk.getIdTaiKhoan(), tk.getTenDangNhap(), tk.getHoTen(), tk.getVaiTro(), khachHangInfo});
        }
    }

    private void deleteSelected() {
        int sel = tableACC.getSelectedRow();
        if (sel < 0) {
            JOptionPane.showMessageDialog(this, "Chọn tài khoản để xóa.");
            return;
        }
        int id = (int) tableACC.getValueAt(sel, 0);
        if (JOptionPane.showConfirmDialog(this, "Xóa tài khoản ID=" + id + " ?", "Xác nhận", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
            return;
        }
        boolean ok = service.delete(id);
        if (ok) {
            loadData();
        } else {
            JOptionPane.showMessageDialog(this, "Không thể xóa tài khoản (có thể là admin duy nhất?).", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void showCreateDialog() {
        JTextField user = new JTextField();
        JPasswordField pass = new JPasswordField();
        JTextField name = new JTextField();
        JComboBox<String> role = new JComboBox<>(new String[]{"admin", "nhanVien", "user"});
        
        List<KhachHang> khachHangList = khachHangService.getAll();
        JComboBox<String> khachHangCombo = new JComboBox<>();
        khachHangCombo.addItem("-- Không liên kết --");
        for (KhachHang kh : khachHangList) {
            khachHangCombo.addItem(kh.getIdKhachHang() + " - " + kh.getTenKhachHang());
        }
        
        Object[] fields = {
            "Tên đăng nhập:", user,
            "Mật khẩu:", pass,
            "Họ tên:", name,
            "Vai trò:", role,
            "Liên kết khách hàng:", khachHangCombo
        };
        int r = JOptionPane.showConfirmDialog(this, fields, "Tạo tài khoản", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (r != JOptionPane.OK_OPTION) {
            return;
        }
        
        Integer idKhachHang = null;
        String selectedKh = (String) khachHangCombo.getSelectedItem();
        if (selectedKh != null && !selectedKh.startsWith("--")) {
            try {
                idKhachHang = Integer.parseInt(selectedKh.split(" - ")[0].trim());
            } catch (NumberFormatException ignored) {}
        }
        
        boolean ok = service.register(user.getText().trim(), new String(pass.getPassword()), name.getText().trim(), (String) role.getSelectedItem(), idKhachHang);
        if (ok) {
            JOptionPane.showMessageDialog(this, "Đã tạo tài khoản.");
            loadData();
        } else {
            JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại hoặc dữ liệu không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void changePasswordForSelectedAccount() {
        int row = tableACC.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(
                        this,
                        "Vui lòng chọn tài khoản cần đổi mật khẩu!",
                        "Thông báo",
                        JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int idTaiKhoan = (int) tableACC.getValueAt(row, 0);
        String username = tableACC.getValueAt(row, 1).toString();
        String hoTen = tableACC.getValueAt(row, 2).toString();

        JPasswordField txtNewPwd = new JPasswordField();
        JPasswordField txtConfirmPwd = new JPasswordField();

        Object[] fields = {
            "Tài khoản: " + username,
            "Họ tên: " + hoTen,
            "Mật khẩu mới:", txtNewPwd,
            "Xác nhận mật khẩu:", txtConfirmPwd
        };

        int result = JOptionPane.showConfirmDialog(
                    this,
                    fields,
                    "Đổi mật khẩu tài khoản",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.PLAIN_MESSAGE
        );

        if (result != JOptionPane.OK_OPTION) {
            return;
        }

        String newPwd = new String(txtNewPwd.getPassword());
        String confirmPwd = new String(txtConfirmPwd.getPassword());

        try {
            boolean ok = service.adminChangePassword(idTaiKhoan, newPwd, confirmPwd);
            if (ok) {
                JOptionPane.showMessageDialog(
                            this,
                            "Đổi mật khẩu thành công!",
                            "Thông báo",
                            JOptionPane.INFORMATION_MESSAGE
                );
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(
                        this,
                        ex.getMessage(),
                        "Lỗi",
                        JOptionPane.ERROR_MESSAGE
            );
        }
    }

}
